### ISSUE TITLE
panic: runtime error: index out of range [1] with length 0 

### ISSUE THREAD

**Issue by probonopd** [MuhammedKpln/chob#26]
```
%  ./Desktop/chob scribus
⚡ Complaining about slow search results? Try caching results by adding --enableCache argument at the end of your command!                                                   
panic: runtime error: index out of range [1] with length 0                            

goroutine 1 [running]:
chobb/modules.SearchInsideAppImages(0x7fffffffdb7f, 0x7)
        /home/muhammed/chob/modules/manager.go:196 +0x395
chobb/modules.SearchForApplication(0x7fffffffdb7f, 0x7)
        /home/muhammed/chob/modules/manager.go:141 +0x50
main.main()
        /home/muhammed/chob/main.go:56 +0x38e
```

**Comment by probonopd** [comment]
Full disclosure: I am running this on FreeBSD using the Linuxulator:

```
% uname -v
FreeBSD 12.1-RELEASE-p13 GENERIC
```

**Comment by MuhammedKpln** [comment]
Release only includes build for Linux, added build for FreeBSD. Can you try again?

**Comment by probonopd** [comment]
Same:

```
% ./Desktop/chob-freebsd scribus
⚡ Complaining about slow search results? Try caching results by adding --enableCache argument at the end of your command!
panic: runtime error: index out of range [1] with length 0

goroutine 1 [running]:
chobb/modules.SearchInsideAppImages(0x7fffffffeb27, 0x7)
        /Users/muhammed/Documents/chob/modules/manager.go:196 +0x395
chobb/modules.SearchForApplication(0x7fffffffeb27, 0x7)
        /Users/muhammed/Documents/chob/modules/manager.go:141 +0x50
main.main()
        /Users/muhammed/Documents/chob/main.go:56 +0x38e
```

**Comment by probonopd** [comment]
It seems to depend on what you search: "Scribus" crashes, "Scribusss" does _not_ crash.

**Comment by MuhammedKpln** [comment]
Oh, I got it. When it does not find any application, it just crashes.

**Comment by MuhammedKpln** [comment]
Can you please try latest version? It should be fixed by now.
